name: models
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core_platform_interface: 4.8.0

