name: repositories
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  services:
    path: ../services
  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter

